name: Build and deploy slatebox-prod to linode k8
on:
  push:
    branches:
      - docker
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          cd ./web
          # docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest .
          # docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          export ROOT_URL_SECRET=$(echo ${{ secrets.ROOT_URL }} | base64 -w 0)
          export MONGO_URL_SECRET=$(echo ${{ secrets.MONGO_URL }} | base64 -w 0)
          export MONGO_OPLOG_URL_SECRET=$(echo ${{ secrets.MONGO_OPLOG_URL }} | base64 -w 0)
          export PORT_SECRET=$(echo ${{ secrets.PORT }} | base64 -w 0)
          export METEOR_SETTINGS_SECRET=$(echo ${{ secrets.METEOR_SETTINGS }} | base64 -w 0)
          echo "ROOT_URL_SECRET: $ROOT_URL_SECRET MONGO_URL_SECRET: $MONGO_URL_SECRET MONGO_OPLOG_URL_SECRET: $MONGO_OPLOG_URL_SECRET PORT_SECRET: $PORT_SECRET METEOR_SETTINGS_SECRET: $METEOR_SETTINGS_SECRET"
          sed -i'' -e 's/DOCKER_HUB_USERNAME/${{ secrets.DOCKER_HUB_USERNAME }}/g' -e 's/DOCKER_HUB_REPOSITORY/${{ secrets.DOCKER_HUB_REPOSITORY }}/g' -e 's/IMAGE_LABEL/latest/g' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" -e "s/ROOT_URL_SECRET/$ROOT_URL_SECRET/g" ./k8.yml
          echo "k8 is"
          cat ./k8.yml
          echo "done k8"
          kubectl apply -f ./k8.yml
        