name: Build and deploy slatebox-test to hetner k3
on:
  push:
    branches:
      - test
jobs:
  build-and-deploy-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.HETZNER_KUBE_CONFIG }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          export RELEASE=$(awk -F'[*…]' '/###*/{print $(NF-1)}' CHANGELOG.md | xargs | awk '{split($0, array, /##/); print array[3]}' | xargs | awk '{split($0, a, /-/); print a[1]}' | xargs | awk '{sub(/\[/,"")sub(/\]/,"")}1' $1)

          cd ./web
          docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}:$RELEASE .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}:$RELEASE
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}:$RELEASE ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}:latest

          # set up sb secrets
          sed -i'' -e "s/TEST_ROOT_URL_SECRET/${{ secrets.TEST_ROOT_URL }}/g"  -e "s/TEST_MONGO_URL_SECRET/${{ secrets.TEST_MONGO_URL }}/g"  -e "s/TEST_MONGO_OPLOG_URL_SECRET/${{ secrets.TEST_MONGO_OPLOG_URL }}/g"  -e "s/TEST_PORT_SECRET/${{ secrets.TEST_PORT }}/g"  -e "s/TEST_METEOR_SETTINGS_SECRET/${{ secrets.TEST_METEOR_SETTINGS }}/g" ./k3/test.yml

          # set up docker creds
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e 's/DOCKER_HUB_USERNAME/${{ secrets.DOCKER_HUB_USERNAME }}/g' -e 's/DOCKER_HUB_TEST_REPOSITORY/${{ secrets.DOCKER_HUB_TEST_REPOSITORY }}/g' -e "s/IMAGE_LABEL/$RELEASE/g" -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" ./k3/test.yml

          # apply both
          kubectl apply -f ./k3/test.yml
