name: Create release when a tag is pushed to main
on:
  push:
    branches:
      - main
      tags:
        - "*"
jobs:
  create-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: "v${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
