name: Create beta release when beta tag is pushed
on:
  push:
    tags:
      - v.beta.*
jobs:
  create-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: "v.beta.${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
