name: Push to docker hub
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    tags:
      - "*"
jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_COMMUNITY_ACCESS_TOKEN }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          cd ./web
          docker build --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_COMMUNITY_REPOSITORY }}:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_COMMUNITY_REPOSITORY }}:${{ github.ref_name }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_COMMUNITY_REPOSITORY }}:${{ github.ref_name }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_COMMUNITY_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_COMMUNITY_REPOSITORY }}:latest
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: "v${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
