version: '3'

services:
  app:
    deploy:
      resources:
        limits:
          memory: 8gb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${BASE_PORT:-2006}:2006'
    extra_hosts:
      - "sb-mongo-1 sb-mongo-1.slatebox.com:192.168.128.66"
      - "sb-mongo-2 sb-mongo-2.slatebox.com:192.168.198.90"
      - "sb-mongo-3 sb-mongo-3.slatebox.com:192.168.220.24"

volumes:
  data: