version: "3"

services:
  app:
    image: timheckel/slatebox-community:latest
    container_name: slatebox-community
    ports:
      - "80:3000"
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/meteor}
      PORT: 3000
      METEOR_SETTINGS: >
        {
          "nounProject": {
            "key": "${NOUN_PROJECT_KEY}",
            "secret": "${NOUN_PROJECT_SECRET}"
          },
          "chatWoot": {
            "userIdentityValidationToken": "${CHATWOOT_TOKEN}"
          },
          "mailGun": {
            "server": "${MAIL_URL}"
          },
          "daily": {
            "apiKey": "${DAILY_API_KEY}"
          },
          "aws": {
            "secretKey": "${AWS_SECRET_KEY}",
            "accessKey": "${AWS_ACCESS_KEY}",
            "imageBucket": "${AWS_S3_IMAGE_BUCKET}",
            "cloudUrl": "${IMAGE_CLOUD_URL}"
          },
          "googleDocs": {
            "web": {
              "client_id": "${GOOGLE_DOCS_CLIENT_ID}",
              "project_id": "${GOOGLE_DOCS_PROJECT_ID}",
              "auth_uri": "${GOOGLE_DOCS_AUTH_URI}",
              "token_uri": "${GOOGLE_DOCS_TOKEN_URI}",
              "auth_provider_x509_cert_url": "${GOOGLE_DOCS_AUTH_PROVIDER_X509_CERT_URL}",
              "client_secret": "${GOOGLE_DOCS_CLIENT_SECRET}",
              "redirect_uris": ["${GOOGLE_DOCS_REDIRECT_URIS}"],
              "javascript_origins": ["${GOOGLE_DOCS_JAVASCRIPT_ORIGINS}"]
            }
          },
          "public": {
            "env": "${MAIL_URL:-dev}",
            "dailyBaseUrl": "${DAILY_URL}",
            "baseUrl": "${BASE_URL:-http://localhost:3000}",
            "googleFontAPIKey": "${GOOGLE_API_KEY}",
            "googleImageSearchEngineKey": "${GOOGLE_IMAGE_SEARCH_API_KEY}",
            "googleImageSearchAPIKey": "${GOOGLE_API_KEY}",
            "pixabayAPIKey": "${PIXABAY_API_KEY}"
          }
        }
  mongo:
    image: mongo:latest
    container_name: mongo-slatebox
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
