# This section will create a secret in the Kubernetes cluster.
# We need this for private docker repos.
apiVersion: v1
kind: Secret
metadata:
  name: slateboxcreds
data:
  .dockerconfigjson: DOCKER_CONFIG
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  ROOT_URL: ROOT_URL_SECRET
  MONGO_URL: MONGO_URL_SECRET
  MONGO_OPLOG_URL: MONGO_OPLOG_URL_SECRET
  PORT: PORT_SECRET
  METEOR_SETTINGS: METEOR_SETTINGS_SECRET
kind: Secret
metadata:
  name: slateboxenvs
---
# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slatebox-deploy
  labels:
    app: slatebox-prod
spec:
  selector:
    matchLabels:
      app: slatebox-prod
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: slatebox-prod
    spec:
      containers:
      - name: slatebox-prod
        image: timheckel/slatebox-prod:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      hostAliases:
      - ip: "192.168.128.66"
        hostnames:
        - "sb-mongo-1"
        - "sb-mongo-1.slatebox.com"
      - ip: "192.168.198.90"
        hostnames:
        - "sb-mongo-2"
        - "sb-mongo-2.slatebox.com"
      - ip: "192.168.220.24"
        hostnames:
        - "sb-mongo-3"
        - "sb-mongo-3.slatebox.com"
      - ip: "192.168.208.125"
        hostnames:
        - "sb-redis-oplog"
      imagePullSecrets:
        - name: slateboxcreds
      - env:
        - name: ROOT_URL
          valueFrom:
            secretKeyRef:
              key: ROOT_URL
              name: slateboxenvs
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              key: MONGO_URL
              name: slateboxenvs
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              key: MONGO_OPLOG_URL
              name: slateboxenvs
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: PORT
              name: slateboxenvs
        - name: METEOR_SETTINGS
          valueFrom:
            secretKeyRef:
              key: METEOR_SETTINGS
              name: slateboxenvs
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: slatebox-loadbalancer
  labels:
    app: slatebox-prod
spec:
  type: LoadBalancer
  selector:
    app: slatebox-prod
  ports:
    - protocol: TCP
      name: http
      port: 443
      targetPort: 3000