apiVersion: v1
kind: Secret
metadata:
  name: slateboxenvs
data:
  ROOT_URL: ROOT_URL_SECRET
  MONGO_URL: MONGO_URL_SECRET
  MONGO_OPLOG_URL: MONGO_OPLOG_URL_SECRET
  PORT: PORT_SECRET
  METEOR_SETTINGS: METEOR_SETTINGS_SECRET